title: "MTN.fire"
description: "Testimony. Fire. Hope. A podcast carrying the fire of God into everyday life."
author: "Matt Culbertson"
timezone: America/New_York

# Preview values (GitHub Pages preview)
url: https://mtnfire.org
baseurl: ""
# When you move to your domain, switch to:
# url: https://mtnfire.org
# baseurl: ""

markdown: kramdown
permalink: /:categories/:title/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

# Used by jekyll-seo-tag
logo: "/logo.png"                # small square logo for structured data
image: "/assets/img/og.jpg"      # 1200x630 default share image (create this or comment out)

# Social profiles for SEO (jekyll-seo-tag reads these)
social:
  links:
    - https://www.facebook.com/MTN.fire86/
    - https://www.youtube.com/@MTN-fire

# Cloudflare Web Analytics (optional)
cloudflare_analytics_token: "0c9d2d00aca44ce6a156791272f79442"

# Podcast directories (used for buttons)
podcast:
  rss:     "https://anchor.fm/s/103bdda2c/podcast/rss"
  apple:   "https://podcasts.apple.com/us/podcast/id1809171724?mt=2&ls=1"
  spotify: "https://open.spotify.com/show/6uoU1NT8OeoFoYmekrzHVe"
  amazon:  "https://music.amazon.com/es-cl/podcasts/b81bf24f-4d9b-468f-b306-2459da4d0eb7/mtn-fire"
  youtube: "https://music.youtube.com/playlist?list=PLIIH4tvdLWqC6Rhqp8YOxRYrqvj4_23aX&si=9GeTgSopdPPMf4u9"
  iheart:        "https://www.iheart.com/podcast/1333-mtnfire-272950909/"
  podcastaddict: "https://podcastaddict.com/podcast/mtnfire/6051511"
  spreaker:      "https://www.spreaker.com/podcast/mtn-fire--6711600"
  pandora:       "https://www.pandora.com/podcast/mtnfire/PC:1001108008"
  castbox:       "https://castbox.fm/vh/6572502"
  podchaser:     "https://www.podchaser.com/podcasts/mtnfire-6069397"

# Socials for header/footer icons include
socials:
  facebook:  "https://www.facebook.com/MTN.fire86"
  youtube:   "https://www.youtube.com/@mtn-fire"
  instagram: "https://www.instagram.com/mtn.fire/"
  tiktok:    "https://www.tiktok.com/@mtn.fire"
  email:     "mailto:mtn.fire86@gmail.com"

# Branding for the header logo
logo_image: "/logo.png"

# Keep dev-only stuff out of the built site
exclude:
  - scripts/
  - Gemfile
  - Gemfile.lock
  - README.md
