title: MTN.fire
description: Testimony, fire, and hope from the mountains.
url: https://mtnfire.github.io
baseurl: /mtnfire.org
author: Matt Culbertson
timezone: America/New_York

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

markdown: kramdown
permalink: /:categories/:title/

# Social links for SEO
social:
  links:
    - https://www.facebook.com/MTN.fire86/
    - https://www.youtube.com/@MTN-fire

# Add your Cloudflare Web Analytics token below (optional)
cloudflare_analytics_token: ""

podcast:
  rss:     "https://anchor.fm/s/103bdda2c/podcast/rss"
  apple:   "https://podcasts.apple.com/us/podcast/id1809171724?mt=2&ls=1"
  spotify: "https://open.spotify.com/show/6uoU1NT8OeoFoYmekrzHVe"
  amazon:  "https://music.amazon.com/es-cl/podcasts/b81bf24f-4d9b-468f-b306-2459da4d0eb7/mtn-fire"
  youtube: "https://music.youtube.com/playlist?list=PLIIH4tvdLWqC6Rhqp8YOxRYrqvj4_23aX&si=9GeTgSopdPPMf4u9"

  iheart:        "https://www.iheart.com/podcast/1333-mtnfire-272950909/"
  podcastaddict: "https://podcastaddict.com/podcast/mtnfire/6051511"
  spreaker:      "https://www.spreaker.com/podcast/mtn-fire--6711600"
  pandora:       "https://www.pandora.com/podcast/mtnfire/PC:1001108008"
  castbox:       "https://castbox.fm/vh/6572502"
  podchaser:     "https://www.podchaser.com/podcasts/mtnfire-6069397"

  
logo_image: "/logo.png"   # since logo.png is at the repo root

socials:
  facebook: "https://www.facebook.com/MTN.fire86"
  youtube:  "https://www.youtube.com/mtnfire"
  instagram:  "https://www.instagram.com/mtn.fire/"
  tiktok:   "https://www.tiktok.com/@mtn.fire"
  email: "mailto:mtn.fire86@gmail.com"   # optional, like: "mailto:you@mtnfire.org"

  title: "MTN.fire"
description: "Testimony. Fire. Hope. A podcast carrying the fire of God into everyday life."

# Preview values (flip these when we move to mtnfire.org)
url: https://mtnfire.github.io
baseurl: /mtnfire.org

# Used by jekyll-seo-tag
logo: "/logo.png"              # small square is fine
image: "/assets/img/og.jpg"    # 1200x630 default share image (optional but nice)

# Optional social handles (improves Twitter cards, etc.)
# twitter:
#   username: mtnfire
# facebook:
#   app_id: "1234567890"       # only if you have one

